// Package service contains the hand-written orchestration endpoints for
// protosource-auth: the login flow that validates credentials and issues
// a shadow token, and the authorization check that dereferences a shadow
// token back to an authenticated user + forwarded JWT.
//
// The aggregates underneath are all generated by protosource — this
// package is the thin orchestration layer that cannot itself be a single
// command because login spans User credential verification, Issuer
// lookup, Key generation/loading, JWT signing, and Token issuance.
package service

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/funinthecloud/protosource"

	"github.com/funinthecloud/protosource-auth/credentials"
	issuerv1 "github.com/funinthecloud/protosource-auth/gen/auth/issuer/v1"
	tokenv1 "github.com/funinthecloud/protosource-auth/gen/auth/token/v1"
	userv1 "github.com/funinthecloud/protosource-auth/gen/auth/user/v1"
	"github.com/funinthecloud/protosource-auth/keys"
)

// DefaultTokenTTL is the shadow-token lifetime: how long the opaque
// bearer is valid and how long the embedded JWT's `exp` claim is pushed
// out from `iat`. Matches the Token aggregate's event_ttl_seconds.
const DefaultTokenTTL = 10 * time.Hour

// DefaultAccessTTL is the short lifetime of an offline-verifiable access
// JWT minted by [Loginer.IssueAccessToken]. It is intentionally far
// shorter than the shadow token: the access JWT is fire-and-forget and
// JWKS-verifiable without a /authz/check hop, so its TTL *is* its
// revocation window. The shadow token remains the instant-revoke handle
// (a revoked shadow simply stops minting fresh access tokens).
const DefaultAccessTTL = 10 * time.Minute

// AccessTokenUse is the value of the "token_use" claim that marks a JWT
// as a short-lived access token (as opposed to the shadow token's
// internal embedded JWT, which carries no token_use). [VerifyAccessToken]
// requires this claim, so the two JWT kinds can never be confused.
const AccessTokenUse = "access"

// Error sentinels returned by Loginer.Login.
var (
	// ErrInvalidCredentials is returned when the email is not found or
	// the password does not match. The two failure modes are intentionally
	// indistinguishable to callers to avoid email enumeration.
	ErrInvalidCredentials = errors.New("service: invalid credentials")
	// ErrUserNotActive is returned when credentials match but the User
	// aggregate is in a state that forbids login (locked, deleted, ...).
	ErrUserNotActive = errors.New("service: user not active")
	// ErrIssuerNotActive is returned when the requested issuer is not in
	// STATE_ACTIVE or is not a SELF issuer (external issuers cannot
	// mint tokens here).
	ErrIssuerNotActive = errors.New("service: issuer not active or not KIND_SELF")
)

// UserDirectory is the narrow lookup the Loginer needs to turn an email
// into a user id. Concrete implementations can call the generated
// UserClient's GSI1 email query for DynamoDB, a hand-maintained index for
// local development, or a direct map for tests.
type UserDirectory interface {
	FindByEmail(ctx context.Context, email string) (userID string, err error)
}

// AggregateRepo is the narrow dependency the Loginer needs from each of
// its backing repositories — a subset of [protosource.Repo] covering
// Apply and Load. Satisfied by the generated *pkgmemory.Repository and
// *pkgdynamodb.Repository types.
type AggregateRepo interface {
	Apply(ctx context.Context, cmd protosource.Commander) (int64, error)
	Load(ctx context.Context, aggregateID string) (protosource.Aggregate, error)
}

// Loginer executes the credential-verify → key-sign → token-issue flow.
type Loginer struct {
	userRepo   AggregateRepo
	issuerRepo AggregateRepo
	tokenRepo  AggregateRepo
	directory  UserDirectory
	resolver   *keys.Resolver

	clock    func() time.Time
	tokenTTL time.Duration

	// accessTTL is the lifetime of access JWTs minted by
	// IssueAccessToken; accessAudience overrides their "aud" claim
	// (empty → defaults to the SELF issuer's iss at mint time).
	accessTTL      time.Duration
	accessAudience string

	// actor is the audit principal recorded on Token.Issue commands
	// produced by this Loginer. Defaults to "loginer".
	actor string
}

// LoginerOption mutates a Loginer at construction time.
type LoginerOption func(*Loginer)

// WithLoginerClock replaces the loginer's time source.
func WithLoginerClock(clock func() time.Time) LoginerOption {
	return func(l *Loginer) { l.clock = clock }
}

// WithTokenTTL overrides how long issued tokens live (both the Token
// aggregate's expires_at and the JWT's exp claim).
func WithTokenTTL(ttl time.Duration) LoginerOption {
	return func(l *Loginer) { l.tokenTTL = ttl }
}

// WithAccessTTL overrides the lifetime of access JWTs minted by
// IssueAccessToken. A non-positive ttl is ignored.
func WithAccessTTL(ttl time.Duration) LoginerOption {
	return func(l *Loginer) {
		if ttl > 0 {
			l.accessTTL = ttl
		}
	}
}

// WithAccessAudience overrides the "aud" claim on minted access JWTs.
// Empty leaves the default (the SELF issuer's iss).
func WithAccessAudience(aud string) LoginerOption {
	return func(l *Loginer) { l.accessAudience = aud }
}

// WithLoginerActor overrides the principal recorded on Token.Issue.
func WithLoginerActor(actor string) LoginerOption {
	return func(l *Loginer) { l.actor = actor }
}

// NewLoginer wires a Loginer with its dependencies. All repos, the
// directory, and the resolver are required; passing nil for any of them
// panics with a descriptive message, consistent with protosource.New.
func NewLoginer(
	userRepo AggregateRepo,
	issuerRepo AggregateRepo,
	tokenRepo AggregateRepo,
	directory UserDirectory,
	resolver *keys.Resolver,
	opts ...LoginerOption,
) *Loginer {
	if userRepo == nil {
		panic("service.NewLoginer: userRepo must not be nil")
	}
	if issuerRepo == nil {
		panic("service.NewLoginer: issuerRepo must not be nil")
	}
	if tokenRepo == nil {
		panic("service.NewLoginer: tokenRepo must not be nil")
	}
	if directory == nil {
		panic("service.NewLoginer: directory must not be nil")
	}
	if resolver == nil {
		panic("service.NewLoginer: resolver must not be nil")
	}
	l := &Loginer{
		userRepo:   userRepo,
		issuerRepo: issuerRepo,
		tokenRepo:  tokenRepo,
		directory:  directory,
		resolver:   resolver,
		clock:      time.Now,
		tokenTTL:   DefaultTokenTTL,
		accessTTL:  DefaultAccessTTL,
		actor:      "loginer",
	}
	for _, opt := range opts {
		opt(l)
	}
	return l
}

// LoginRequest is the input to [Loginer.Login].
type LoginRequest struct {
	Email    string
	Password string
	IssuerID string
}

// LoginResponse is the output of a successful [Loginer.Login].
type LoginResponse struct {
	// UserID is the authenticated user's id (the subject of the JWT).
	// Exposed so browser callers (loginpage, oauth callback) can mint a
	// companion access JWT without re-deriving the identity.
	UserID string
	// ShadowToken is the opaque bearer handed back to the caller. It is
	// also the aggregate id of the underlying Token record.
	ShadowToken string
	// JWT is the signed JWT embedded in the Token aggregate. Returned so
	// downstream callers that bypass the /authz/check path can use it
	// directly (e.g. tests, local development).
	JWT string
	// ExpiresAt is the Unix-second expiration of both the shadow token
	// and the JWT.
	ExpiresAt int64
}

// Login validates the credentials, loads the (SELF) issuer, signs a fresh
// JWT via the key resolver, creates a Token aggregate keyed by a new
// opaque GUID, and returns the result.
//
// All authentication failures return ErrInvalidCredentials regardless of
// whether the cause was a missing email or a password mismatch, to avoid
// leaking which accounts exist.
func (l *Loginer) Login(ctx context.Context, req LoginRequest) (*LoginResponse, error) {
	userID, err := l.directory.FindByEmail(ctx, req.Email)
	if err != nil || userID == "" {
		return nil, ErrInvalidCredentials
	}

	userAgg, err := l.userRepo.Load(ctx, userID)
	if err != nil {
		return nil, ErrInvalidCredentials
	}
	user, ok := userAgg.(*userv1.User)
	if !ok {
		return nil, fmt.Errorf("service: loaded user is %T, want *userv1.User", userAgg)
	}

	if user.GetState() != userv1.State_STATE_ACTIVE {
		return nil, ErrUserNotActive
	}

	if err := credentials.Verify(user.GetPasswordHash(), req.Password); err != nil {
		return nil, ErrInvalidCredentials
	}

	issuer, err := l.loadSelfIssuer(ctx, req.IssuerID)
	if err != nil {
		return nil, err
	}

	return l.mintShadowToken(ctx, user.GetId(), req.IssuerID, issuer)
}

// IssueForUser mints a shadow token for an already-authenticated local user,
// skipping the password/credential check. It is the hand-off point for the
// federated-login (PKCE) callback: once an external IdP's ID token has been
// verified and mapped to a local user id (see [IdentityResolver]), the
// callback calls this to mint the same kind of shadow token + JWT that
// [Loginer.Login] produces for the password flow.
//
// selfIssuerID names the SELF issuer whose key signs the JWT (the same issuer
// the password flow uses); it is loaded and validated (STATE_ACTIVE +
// KIND_SELF) exactly like Login, so the iss/default-algorithm come from the
// aggregate, not the caller. userID is trusted — the caller is responsible
// for having authenticated it.
func (l *Loginer) IssueForUser(ctx context.Context, userID, selfIssuerID string) (*LoginResponse, error) {
	if userID == "" {
		return nil, fmt.Errorf("service: IssueForUser: userID must not be empty")
	}
	issuer, err := l.loadSelfIssuer(ctx, selfIssuerID)
	if err != nil {
		return nil, err
	}
	return l.mintShadowToken(ctx, userID, selfIssuerID, issuer)
}

// loadSelfIssuer loads the issuer and verifies it is an ACTIVE KIND_SELF
// issuer (only SELF issuers mint our shadow tokens). Shared by Login and
// IssueForUser.
func (l *Loginer) loadSelfIssuer(ctx context.Context, issuerID string) (*issuerv1.Issuer, error) {
	issuerAgg, err := l.issuerRepo.Load(ctx, issuerID)
	if err != nil {
		return nil, fmt.Errorf("service: load issuer: %w", err)
	}
	issuer, ok := issuerAgg.(*issuerv1.Issuer)
	if !ok {
		return nil, fmt.Errorf("service: loaded issuer is %T, want *issuerv1.Issuer", issuerAgg)
	}
	if issuer.GetState() != issuerv1.State_STATE_ACTIVE || issuer.GetKind() != issuerv1.Kind_KIND_SELF {
		return nil, ErrIssuerNotActive
	}
	return issuer, nil
}

// mintShadowToken is the shared claims→sign→Apply body used by both the
// password (Login) and federated (IssueForUser) flows: it generates an opaque
// token id, signs a JWT with the SELF issuer's current key, and persists the
// Token aggregate. The caller has already authenticated userID and validated
// the issuer.
func (l *Loginer) mintShadowToken(ctx context.Context, userID, issuerID string, issuer *issuerv1.Issuer) (*LoginResponse, error) {
	now := l.clock()
	expiresAt := now.Add(l.tokenTTL)

	tokenID, err := generateOpaqueToken()
	if err != nil {
		return nil, fmt.Errorf("service: generate token id: %w", err)
	}

	claims := map[string]any{
		"iss": issuer.GetIss(),
		"sub": userID,
		"aud": issuer.GetIss(),
		"iat": now.Unix(),
		"exp": expiresAt.Unix(),
		"jti": tokenID,
	}
	claimsJSON, err := json.Marshal(claims)
	if err != nil {
		return nil, fmt.Errorf("service: marshal claims: %w", err)
	}

	signingKey, err := l.resolver.SigningKey(ctx, issuerID, issuer.GetDefaultAlgorithm())
	if err != nil {
		return nil, fmt.Errorf("service: resolve signing key: %w", err)
	}
	jwt, err := signingKey.Sign(claimsJSON)
	if err != nil {
		return nil, fmt.Errorf("service: sign jwt: %w", err)
	}

	if _, err := l.tokenRepo.Apply(ctx, &tokenv1.Issue{
		Id:        tokenID,
		Actor:     l.actor,
		UserId:    userID,
		IssuerId:  issuerID,
		Jwt:       jwt,
		IssuedAt:  now.Unix(),
		ExpiresAt: expiresAt.Unix(),
	}); err != nil {
		return nil, fmt.Errorf("service: apply token issue: %w", err)
	}

	return &LoginResponse{
		UserID:      userID,
		ShadowToken: tokenID,
		JWT:         jwt,
		ExpiresAt:   expiresAt.Unix(),
	}, nil
}

// IssueAccessToken mints a short-lived, offline-verifiable access JWT for
// an already-authenticated user. Unlike the shadow token's internal JWT
// (which is never returned to network callers), the access JWT is
// deliberately handed to the caller and verified offline against the
// SELF issuer's JWKS (/oauth/jwks) — see [VerifyAccessToken]. It carries
// a "token_use":"access" claim so it can never be mistaken for the
// shadow's embedded JWT, and a short TTL ([DefaultAccessTTL]) that is its
// only revocation window: the shadow token remains the instant-revoke
// handle.
//
// It is identity-only: the subject is the local user id. Function-grant
// authorization stays with /authz/check + the shadow token; the access
// JWT only tells a downstream service *who* the caller is without a
// round-trip. selfIssuerID names the SELF issuer whose key signs it
// (loaded + validated exactly like [Loginer.IssueForUser]).
func (l *Loginer) IssueAccessToken(ctx context.Context, userID, selfIssuerID string) (jwt string, expiresAt int64, err error) {
	if userID == "" {
		return "", 0, fmt.Errorf("service: IssueAccessToken: userID must not be empty")
	}
	issuer, err := l.loadSelfIssuer(ctx, selfIssuerID)
	if err != nil {
		return "", 0, err
	}

	now := l.clock()
	exp := now.Add(l.accessTTL)

	jti, err := generateOpaqueToken()
	if err != nil {
		return "", 0, fmt.Errorf("service: generate access jti: %w", err)
	}

	aud := l.accessAudience
	if aud == "" {
		aud = issuer.GetIss()
	}

	claims := map[string]any{
		"iss":       issuer.GetIss(),
		"sub":       userID,
		"aud":       aud,
		"iat":       now.Unix(),
		"exp":       exp.Unix(),
		"jti":       jti,
		"token_use": AccessTokenUse,
	}
	claimsJSON, err := json.Marshal(claims)
	if err != nil {
		return "", 0, fmt.Errorf("service: marshal access claims: %w", err)
	}

	signingKey, err := l.resolver.SigningKey(ctx, selfIssuerID, issuer.GetDefaultAlgorithm())
	if err != nil {
		return "", 0, fmt.Errorf("service: resolve signing key: %w", err)
	}
	signed, err := signingKey.Sign(claimsJSON)
	if err != nil {
		return "", 0, fmt.Errorf("service: sign access jwt: %w", err)
	}
	return signed, exp.Unix(), nil
}

// generateOpaqueToken produces a URL-safe random token id suitable for
// use as both the aggregate key and the value bearers hand back on each
// request. 32 bytes of crypto/rand gives ~256 bits of entropy and a
// 43-character base64url representation.
func generateOpaqueToken() (string, error) {
	var buf [32]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(buf[:]), nil
}
