// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource-auth/gen/auth/issuer/v1"
	"github.com/funinthecloud/protosource-auth/gen/auth/issuer/v1/issuerv1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/key/v1"
	"github.com/funinthecloud/protosource-auth/gen/auth/key/v1/keyv1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/role/v1"
	"github.com/funinthecloud/protosource-auth/gen/auth/role/v1/rolev1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/token/v1"
	"github.com/funinthecloud/protosource-auth/gen/auth/token/v1/tokenv1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/user/v1"
	"github.com/funinthecloud/protosource-auth/gen/auth/user/v1/userv1dynamodb"
	"github.com/funinthecloud/protosource-auth/keyproviders"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/dynamodbstore"
)

// Injectors from wire.go:

// InitializeRouter wires all dependencies and returns a configured
// router ready for awslambda.WrapRouter.
func InitializeRouter(client *dynamodb.Client, eventsTable dynamodbstore.EventsTableName, aggregatesTable dynamodbstore.AggregatesTableName, keyProvider keyproviders.KeyProvider, masterKeyRef MasterKeyRef) (*protosource.Router, error) {
	store := dynamodbstore.ProvideOpaqueStore(client, aggregatesTable)
	dynamoDBStore, err := dynamodbstore.ProvideStore(client, store, eventsTable)
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := userv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	issuerv1dynamodbRepository := issuerv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	tokenv1dynamodbRepository := tokenv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	userClient := userv1.NewUserClient(store)
	userDirectory := provideDirectory(userClient)
	keyv1dynamodbRepository := keyv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	resolver := provideResolver(keyv1dynamodbRepository, keyProvider, masterKeyRef)
	loginer := provideLoginer(repository, issuerv1dynamodbRepository, tokenv1dynamodbRepository, userDirectory, resolver)
	rolev1dynamodbRepository := rolev1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	checker := provideChecker(tokenv1dynamodbRepository, repository, rolev1dynamodbRepository)
	service := provideService(loginer, checker)
	page := providePage(loginer)
	whoami := provideWhoami(tokenv1dynamodbRepository, repository)
	authorizer := provideAuthorizer(checker)
	handler := provideUserHandler(repository, userClient, authorizer)
	roleClient := rolev1.NewRoleClient(store)
	rolev1Handler := provideRoleHandler(rolev1dynamodbRepository, roleClient, authorizer)
	issuerClient := issuerv1.NewIssuerClient(store)
	issuerv1Handler := provideIssuerHandler(issuerv1dynamodbRepository, issuerClient, authorizer)
	keyClient := keyv1.NewKeyClient(store)
	keyv1Handler := provideKeyHandler(keyv1dynamodbRepository, keyClient, authorizer)
	tokenClient := tokenv1.NewTokenClient(store)
	tokenv1Handler := provideTokenHandler(tokenv1dynamodbRepository, tokenClient, authorizer)
	corsOrigin := provideCORSOrigin()
	router := provideRouter(service, page, whoami, handler, rolev1Handler, issuerv1Handler, keyv1Handler, tokenv1Handler, corsOrigin)
	return router, nil
}
