// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/funinthecloud/protosource"
	"github.com/funinthecloud/protosource-auth/gen/auth/issuer/v1/issuerv1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/key/v1/keyv1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/role/v1/rolev1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/token/v1/tokenv1dynamodb"
	"github.com/funinthecloud/protosource-auth/gen/auth/user/v1"
	"github.com/funinthecloud/protosource-auth/gen/auth/user/v1/userv1dynamodb"
	"github.com/funinthecloud/protosource/serializers/protobinaryserializer"
	"github.com/funinthecloud/protosource/stores/dynamodbstore"
)

// Injectors from wire.go:

// InitializeRouter wires all dependencies and returns a configured
// router ready for awslambda.WrapRouter.
func InitializeRouter(client *dynamodb.Client, eventsTable dynamodbstore.EventsTableName, aggregatesTable dynamodbstore.AggregatesTableName, masterKey MasterKey, issuerIss IssuerIss) (*protosource.Router, error) {
	store := dynamodbstore.ProvideOpaqueStore(client, aggregatesTable)
	dynamoDBStore, err := dynamodbstore.ProvideStore(client, store, eventsTable)
	if err != nil {
		return nil, err
	}
	serializer := protobinaryserializer.NewSerializer()
	repository := userv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	issuerv1dynamodbRepository := issuerv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	tokenv1dynamodbRepository := tokenv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	userClient := userv1.NewUserClient(store)
	userDirectory := provideDirectory(userClient)
	keyv1dynamodbRepository := keyv1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	keyProvider, err := provideKeyProvider(masterKey)
	if err != nil {
		return nil, err
	}
	resolver := provideResolver(keyv1dynamodbRepository, keyProvider)
	loginer := provideLoginer(repository, issuerv1dynamodbRepository, tokenv1dynamodbRepository, userDirectory, resolver)
	rolev1dynamodbRepository := rolev1dynamodb.ProvideRepository(dynamoDBStore, serializer)
	checker := provideChecker(tokenv1dynamodbRepository, repository, rolev1dynamodbRepository)
	service := provideService(loginer, checker)
	router := provideRouter(service)
	return router, nil
}
